### ISSUE TITLE
Acomodar los reportes PDF

### ISSUE THREAD

**Issue by Gianfranco97** [ProyectoIglesia/Proyecto_Iglesia#2]
Hay que arreglar el apartado de los reportes en PDF. Actualmente el programa genera un archivo con toda la estructura básica que tiene que tener mas sinembargo **no anexa** la información específica que se le exige.

**Comment by Gianfranco97** [comment]
En vista que **no hemos podido solucionar** el problema con la librería _**DOMPDF**_, se plantea el utilizar en su reemplazo _**FPDF**_ para la generación de los reportes.

**Comment by ndvelasquez** [comment]
Ya se solucionó el problema de los reportes **PDF** ahora sólo falta editar un poco mas el código para que imprima el de los trabajadores porque sólo imprime el de estudiantes de forma predeterminada
