### ISSUE TITLE
Mejorar el menú privado

### ISSUE THREAD

**Issue by Gianfranco97** [ProyectoIglesia/Proyecto_Iglesia#5]
El menú privado que tenemos actualmente es un desastre. **Siquiera** tenemos una separación por niveles, los estudiantes **pueden** hacer exactamente lo mismo que un administrador.

**Comment by ndvelasquez** [comment]
Además de la separación por niveles hay que agregar una botonera a la aplicación que tenga por ejemplo "atras", "guardar cambios", "salir", etc

**Comment by Gianfranco97** [comment]
Ya lo de la botonera está resuelto.

**Comment by Gianfranco97** [comment]
El menú privado ya tiene medio camino hecho, **falta todo el nivel de los profesores** y acomodar pequeños detalles de diseño.
